services:
  # PostgreSQL
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - lab3_data_final:/var/lib/postgresql/data
      - ./sql_schema:/docker-entrypoint-initdb.d
    networks:
      - production-network

  # Java Spring Boot App
  app:
    
    profiles: ["docker-only"]
    
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_LOGIN=${DB_LOGIN}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
    depends_on:
      - postgres
    networks:
      - production-network

volumes:
  lab3_data_final:

networks:
  production-network:
    driver: bridge
      - POSTGRES_PASSWORD=newpass  
      - POSTGRES_USER=myuser
    ports:
      - "5433:5432"            
    volumes:
      - lab3_data_final:/var/lib/postgresql/data 
      - ./sql_schema:/docker-entrypoint-initdb.d
volumes:
  lab3_data_final:

