services:
<<<<<<< HEAD
  # PostgreSQL
=======
>>>>>>> 7adadccd91c69313aa7d5caf4e8f22ee1ad413f6
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=mydatabase
<<<<<<< HEAD
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - lab3_data_final:/var/lib/postgresql/data
      - ./sql_schema:/docker-entrypoint-initdb.d
    networks:
      - production-network

  # Java Spring Boot App
  app:
    # ðŸ‘‡ Ð¦ÐµÐ¹ Ñ€ÑÐ´Ð¾Ðº Ð¼Ð°Ñ” Ð±ÑƒÑ‚Ð¸ Ð½Ð° Ñ‚Ð¾Ð¼Ñƒ Ð¶ Ñ€Ñ–Ð²Ð½Ñ– Ð²Ñ–Ð´ÑÑ‚ÑƒÐ¿Ñƒ, Ñ‰Ð¾ Ñ– `build:`, `restart:`
    profiles: ["docker-only"]
    
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_LOGIN=${DB_LOGIN}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
    depends_on:
      - postgres
    networks:
      - production-network

volumes:
  lab3_data_final:

networks:
  production-network:
    driver: bridge
=======
      - POSTGRES_PASSWORD=newpass  
      - POSTGRES_USER=myuser
    ports:
      - "5433:5432"            
    volumes:
      - lab3_data_final:/var/lib/postgresql/data 
      - ./sql_schema:/docker-entrypoint-initdb.d
volumes:
  lab3_data_final:
>>>>>>> 7adadccd91c69313aa7d5caf4e8f22ee1ad413f6
